version: '3.8'
services:
  backend:
    build:
      context: backend

    restart: &restartPolicy 'always'

    logging: &logging
      options:
        max-size: '10M'
        max-file: '3'
    ports:
      - 8000:8000
    networks:
      - app-network


  frontend:
    build: frontend
    restart: *restartPolicy
    logging: *logging
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
